version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

    backend:
      build: 
        context: ./server
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      volumes:
        - ./server:/usr/src/app
      depends_on:
        - mongo

    frontend:
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
      volumes:
        - ./client:/usr/src/app
      depends_on:
        - backend


networks:
  mongo: